### ISSUE TITLE
Config schema is missing

### ISSUE THREAD

**Issue by lamp5** [yannickoo/yaml_editor#18]
Config schema is missing
[yaml_editor-missing_schema.txt](https://github.com/yannickoo/yaml_editor/files/7512238/yaml_editor-missing_schema.txt)
.

**Comment by yannickoo** [comment]
Thank you @lamp5, this has been fixed in https://github.com/yannickoo/yaml_editor/commit/67ce34b69ab93be9789f6e9794d0b7e4cee97bbd
