### ISSUE TITLE
Drupal 10 support

### ISSUE THREAD

**Issue by jurgenhaas** [yannickoo/yaml_editor#19]
There's probably not much that needs to be done. Are you planning to make this available any time soon?

Asking because our module [Config Auto Export](https://www.drupal.org/project/config_auto_export) has yours as a dependency and we really need that.

**Comment by cateprNIH** [comment]
From the Drupal upgrade status module, here are the following changes listed for D10 compatabiilty:

```
YAML Editor 8.x-1.1

2 warnings found.

modules/contrib/yaml_editor/yaml_editor.libraries.yml:
┌──────────┬──────┬──────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                            │
├──────────┼──────┼──────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ The 'yaml_editor' library is depending on a deprecated       │
│ manually │      │ library. The core/jquery.once asset library is deprecated in │
│          │      │ Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the   │
│          │      │ core/once library instead. See                               │
│          │      │ https://www.drupal.org/node/3158256                          │
│          │      │                                                              │
└──────────┴──────┴──────────────────────────────────────────────────────────────┘

modules/contrib/yaml_editor/yaml_editor.info.yml:
┌──────────┬──────┬────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                          MESSAGE                           │
├──────────┼──────┼────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Value of core_version_requirement: ^8 || ^9 is not         │
│ manually │      │ compatible with the next major version of Drupal core. See │
│          │      │ https://drupal.org/node/3070687.                           │
│          │      │                                                            │
└──────────┴──────┴────────────────────────────────────────────────────────────┘

```

#20 add the `core_version_requirement` but looks like the deprecated `core/jquery.once` asset library change still needs to happen.

**Comment by jeremypeter** [comment]
Here's a patch that can be used for now:
[yaml_editor-8.x-1.x-drupal-10-compatibility-fixes.patch](https://github.com/yannickoo/yaml_editor/files/10828868/yaml_editor-8.x-1.x-drupal-10-compatibility-fixes.patch)

- Updates version requirement to be Drupal ^9.3 || ^10
- Refactors JS to remove jQuery in favor of vanilla JS
- Removes jQuery and jQuery Once library dependencies
- Uses Drupal core's `once` library

**Comment by dgwestfall** [comment]
Looking forward to a Drupal 10 compatible YAML editor. Applying the patch left me with a duplicate core_version_requirement line in yaml_editor.info.yml:

core_version_requirement: ^9 || ^10
core_version_requirement: ^8 || ^9

**Comment by summitims** [comment]
+1 for Drupal 10 version on Drupal.org! Thanks, Greetings,

**Comment by politsin** [comment]
up

**Comment by wayne-weibel** [comment]
Any chance someone can pick this module up and merge/release the D10 version?

**Comment by Monikag2603** [comment]
> Here's a patch that can be used for now: [yaml_editor-8.x-1.x-drupal-10-compatibility-fixes.patch](https://github.com/yannickoo/yaml_editor/files/10828868/yaml_editor-8.x-1.x-drupal-10-compatibility-fixes.patch)
> 
> * Updates version requirement to be Drupal ^9.3 || ^10
> * Refactors JS to remove jQuery in favor of vanilla JS
> * Removes jQuery and jQuery Once library dependencies
> * Uses Drupal core's `once` library

Hi @jeremypeter, when I try to apply patch via composer/git it is not working, it is skipping the patch.

**Comment by asgharkhan** [comment]
Any chance D8 version available soon?.

**Comment by jurgenhaas** [comment]
FYI, I've given up on this module and removed its dependency from my own modules. I consider it unmaintained.

**Comment by dgwestfall** [comment]
Did you find another solution?

> FYI, I've given up on this module and removed its dependency from my own modules. I consider it unmaintained.

**Comment by patrickcate** [comment]
> I consider it unmaintained.

One option is to [submit a request to transfer ownership of the module](https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/maintainership/offering-to-become-a-project-owner-maintainer-or-co-maintainer/how-to-become-project-owner-maintainer-or-co) if anyone is interested.

**Comment by jurgenhaas** [comment]
@dgwestfall I went with simple textarea for those few cases where it was needed, and that's for admins only where I accepted the requirement, that they have to be extra careful when entering their data.

@patrickcate if I didn't have 50+ modules to maintain already, that would be a consideration.

**Comment by fago** [comment]
I've offered taking over maintainership!
https://www.drupal.org/project/projectownership/issues/3380204

**Comment by yannickoo** [comment]
Hey sorry for the huge delay on this! The latest dev version is finally supporting D10 version 😇 Everything will be moved to drupal.org so that we can benefit from new tools that are available over there.
