### ISSUE TITLE
Please add permission(s)

### ISSUE THREAD

**Issue by kevinquillen** [yannickoo/yaml_editor#3]
YAML Editor should not be available to any role that has access to the Drupal admin.

Currently the route permission is set to `access administration pages` which is too broad. It should have a permission like `administer yaml editor` on this route instead, so that roles can be assigned such a permission.

**Comment by yannickoo** [comment]
This module is not providing new routes, it's just a better interface for `<textarea>` elements. Do we really need to add another permission here? 🤔

**Comment by yannickoo** [comment]
Thanks!
