### ISSUE TITLE
How to enable editor

### ISSUE THREAD

**Issue by polnetwork** [yannickoo/yaml_editor#7]
Hi, I'm testing the module, I'm on the readme but can't see how to enable the editor as this:

$form['config'] = [
  '#type' => 'textarea',
  '#title' => t('Configuration'),
  '#attributes' => ['data-yaml-editor' => 'true'],
];

Should I set it to the theme config file?
I need it for example on admin/config/menu_link_attributes/config form https://www.drupal.org/project/menu_link_attributes module.

Thank's for all

**Comment by yannickoo** [comment]
Menu Link Attributes already provides support for the YAML Editor so you would just need to have both modules enabled to see the editor for the module config.
